Repository Health-Barbecue-Co/Health-Barbecue, pull requests merged in 2020-04, with the labels that each got.

#26 Update readme
  README.md
Labels: documentation

#29 Add instructions to install and build on macOS
  README.md
Labels: documentation

#41 Business : Implement MongoDB connection + Series Crud
  business/MetadataDatabase/Controllers/BaseController.cs
  business/MetadataDatabase/Controllers/SeriesController.cs
  business/MetadataDatabase/Convertor/SeriesConvertor.cs
  business/MetadataDatabase/Data/SeriesDto.cs
  business/MetadataDatabase/MetadataDatabase.csproj
  business/MetadataDatabase/Models/IModelContext.cs
  business/MetadataDatabase/Models/Series.cs
  business/MetadataDatabase/Models/SeriesContext.cs
  business/MetadataDatabase/Models/SeriesDBSettings.cs
  business/MetadataDatabase/Properties/launchSettings.json
  business/MetadataDatabase/Repository/IRepository.cs
  business/MetadataDatabase/Repository/ISeriesRepository.cs
  business/MetadataDatabase/Repository/SeriesRepository.cs
  business/MetadataDatabase/Services/ICrudService.cs
  business/MetadataDatabase/Services/ISeriesServices.cs
  business/MetadataDatabase/Services/SeriesServices.cs
  business/MetadataDatabase/Startup.cs
  business/MetadataDatabase/appsettings.json
  client/web/src/components/series/list/SeriesList.tsx
  docker-compose.yml
Labels: task

#47 Fix interconnection between API & Database in Docker
  business/MetadataDatabase/.vs/MetadataDatabase/DesignTimeBuild/.gitignore
  business/MetadataDatabase/.vs/MetadataDatabase/v16/.gitignore
  business/MetadataDatabase/appsettings.json
  business/MetadataDatabase/framework/DAL/MongoConfiguration.cs
  business/MetadataDatabase/framework/DAL/MongoRepositoryBase.cs
  docker-compose.yml
Labels: bug

#44 Frontend : implement one interface
  client/web/.eslintrc
  client/web/README.md
  client/web/README_CRA.md
  client/web/package.json
  client/web/public/index.html
  client/web/src/App.tsx
  client/web/src/components/Navbar.tsx
  client/web/src/components/common/Navbar/Navbar.style.ts
  client/web/src/components/common/Navbar/Navbar.tsx
  client/web/src/components/common/index.ts
  client/web/src/components/counter/Counter.tsx
  client/web/src/components/counter/index.ts
  client/web/src/components/series/list/SeriesList.style.ts
  client/web/src/components/series/list/SeriesList.tsx
  client/web/src/components/users/ForgottenPassword/ForgottenPassword.tsx
  client/web/src/components/users/Register/RegisterUser.tsx
  client/web/src/components/users/Signin/SignIn.spec.tsx
  client/web/src/components/users/Signin/SignIn.style.ts
  client/web/src/components/users/Signin/SignIn.tsx
  client/web/src/components/users/index.ts
  client/web/src/config/menu.tsx
  client/web/src/features/counter/actionTypes.ts
  client/web/src/features/counter/counterReducer.spec.ts
  client/web/src/features/counter/counterReducer.ts
  client/web/src/features/counter/selectors.ts
  client/web/src/features/counter/types.ts
  client/web/src/features/user/actionTypes.ts
  client/web/src/features/user/index.ts
  client/web/src/features/user/selectors.ts
  client/web/src/features/user/types.ts
  client/web/src/features/user/userReducer.spec.ts
  client/web/src/features/user/userReducer.ts
  client/web/src/i18n.ts
  client/web/src/index.scss
  client/web/src/index.tsx
  client/web/src/locales/de/translation.json
  client/web/src/locales/de/user.json
  client/web/src/locales/en/translation.json
  client/web/src/locales/en/user.json
  client/web/src/locales/fr/translation.json
  client/web/src/locales/fr/user.json
  client/web/src/locales/ja/translation.json
  client/web/src/locales/ja/user.json
  client/web/src/models/version.ts
  client/web/src/pages/Home.tsx
  client/web/src/pages/Series.tsx
  client/web/src/pages/Studies.tsx
  client/web/src/pages/User.tsx
  client/web/src/store.ts
  client/web/yarn.lock
Labels: task

#50 frontend - redux-saga implementation + unit testing
  client/web/README.md
  client/web/__mocks__/mockAxios.ts
  client/web/__mocks__/react-i18next.tsx
  client/web/package.json
  client/web/src/components/series/list/SeriesList.spec.tsx
  client/web/src/components/series/list/SeriesList.tsx
  client/web/src/components/studies/list/StudiesList.spec.tsx
  client/web/src/components/studies/list/StudiesList.tsx
  client/web/src/components/users/Signin/SignIn.spec.tsx
  client/web/src/features/common/HttpRequest.spec.ts
  client/web/src/features/common/HttpRequest.ts
  client/web/src/features/common/ICrudService.ts
  client/web/src/features/series/actionTypes.ts
  client/web/src/features/series/index.ts
  client/web/src/features/series/selectors.ts
  client/web/src/features/series/seriesReducer.spec.ts
  client/web/src/features/series/seriesReducer.ts
  client/web/src/features/series/seriesSaga.spec.ts
  client/web/src/features/series/seriesSaga.ts
  client/web/src/features/series/seriesService.spec.ts
  client/web/src/features/series/seriesService.ts
  client/web/src/features/series/types.ts
  client/web/src/features/user/actionTypes.ts
  client/web/src/features/user/index.ts
  client/web/src/features/user/types.ts
  client/web/src/features/user/userReducer.ts
  client/web/src/features/user/userSaga.ts
  client/web/src/features/user/userService.ts
  client/web/src/models/series.ts
  client/web/src/models/user.ts
  client/web/src/store.ts
  client/web/yarn.lock
Labels: task
